// <auto-generated />
using System;
using DigitalLibraryFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalLibraryFinal.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("GenreName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Isbn", "GenreName")
                        .HasName("PK__BookGenr__DFC32AD84E5743BF");

                    b.HasIndex("GenreName");

                    b.ToTable("BookGenres", (string)null);
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Author__70DAFC14684D1BD0");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Isbn")
                        .HasName("PK__Book__447D36EBCD9D0DA8");

                    b.HasIndex("PublisherName");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Genre", b =>
                {
                    b.Property<string>("GenreName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GenreName")
                        .HasName("PK__Genre__BBE1C338C3CECAF8");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Publisher", b =>
                {
                    b.Property<string>("PublisherName")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("PublisherName")
                        .HasName("PK__Publishe__5F0E22489624C098");

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("WrittenBy", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.HasKey("Isbn", "AuthorId")
                        .HasName("PK__WrittenB__1370992A17B2EDCC");

                    b.HasIndex("AuthorId");

                    b.ToTable("WrittenBy", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DigitalLibraryFinal.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreName")
                        .IsRequired()
                        .HasConstraintName("FK__BookGenre__Genre__571DF1D5");

                    b.HasOne("DigitalLibraryFinal.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK__BookGenres__ISBN__5629CD9C");
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Book", b =>
                {
                    b.HasOne("DigitalLibraryFinal.Models.Publisher", "PublisherNameNavigation")
                        .WithMany("Books")
                        .HasForeignKey("PublisherName")
                        .IsRequired()
                        .HasConstraintName("FK__Book__PublisherN__4D94879B");

                    b.Navigation("PublisherNameNavigation");
                });

            modelBuilder.Entity("WrittenBy", b =>
                {
                    b.HasOne("DigitalLibraryFinal.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__WrittenBy__Autho__5BE2A6F2");

                    b.HasOne("DigitalLibraryFinal.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK__WrittenBy__ISBN__5CD6CB2B");
                });

            modelBuilder.Entity("DigitalLibraryFinal.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
